@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml
SHOW_PERSON_OUTLINE()

title Container Diagram voor het Trip Top System

Person(reiziger, "Reiziger", "Een persoon die een reis plant en beheert")
Person(reizigerA, "Reiziger Agent", "Biedt ondersteuning voor de reiziger")

System_Boundary(tts, "Trip Top System") {
    Container(fe, "Front-End", "React", "Biedt reisplanningsfunctionaliteit via webbrowser")
    Container(fea, "Front-End (Admin)", "React", "Biedt admin functionaliteit tot de reisplanningsfunctionaliteit via webbrowser")

    Container(be, "Back-End", "Spring Boot", "Behandelt alle businesslogica, communicatie met externe APIs en opslag van gegevens")

    ContainerDb(db, "Database", "H2", "Slaat reisinformatie, boekingen en gebruikersdata op")
}

System_Ext(bapi, "Booking API", "Booking API ")
System_Ext(trapi, "Tripadviser API", "Tripadviser API")

System_Ext(nsapi, "NS API", "Treinreisinformatie van de Nederlandse Spoorwegen")
System_Ext(googleflightsapi, "Google Flights API", "Vluchtreisinformatie via RapidAPI")

Rel(reiziger, fe, "Gebruikt", "HTTPS")
Rel(reizigerA, fea, "Gebruikt", "HTTPS")

Rel(fe, be, "Roept aan", "JSON/HTTPS")
Rel(fea, be, "Roept aan", "JSON/HTTPS")

Rel(be, db, "Leest van en schrijft naar", "JDBC")

Rel(be, trapi, "Haalt hoteldata op van", "JSON/HTTPS")
Rel(be, bapi, "Haalt verblijfdata op van", "JSON/HTTPS")
Rel(be, nsapi, "Haalt treinreisinformatie op van", "JSON/HTTPS")
Rel(be, googleflightsapi, "Haalt vluchtinformatie op van", "JSON/HTTPS")




@enduml
