
@startuml
title Hoe zorgen we ervoor dat `TransportPlanner` flexibel omgaat met verschillende vormen van vervoer


class TransportPlanner {
    +planTransport()
}

class CarTransport {
    +getRoute()
    +getPrice()
    +book()
}

class TrainTransport {
    +getRoute()
    +getPrice()
    +book()
}

class BoatTransport {
    +getRoute()
    +getPrice()
    +book()
}

class planeTransport {
    +getRoute()
    +getPrice()
    +book()
}
class TransportTracker {
    +setStatus()
    +getStatus()
}



TransportPlanner --> CarTransport : uses
TransportPlanner --> TrainTransport : uses
CarTransport --> TransportTracker : updates
TrainTransport --> TransportTracker : updates

TransportPlanner --> planeTransport : uses
TransportPlanner --> BoatTransport : uses
BoatTransport --> TransportTracker : updates
planeTransport --> TransportTracker : updates

@enduml
